services:
  postgresdb:
    image: postgres:18.0-alpine
    environment:
      - POSTGRES_USER=sarpbc
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sarpbc
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-sarpbc:/var/lib/postgresql/data
    networks:
      - sarpbc_net

  redis:
    image: redis:7.4-alpine
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6380:6379"
    volumes:
      - redis-data-sarpbc:/data
    networks:
      - sarpbc_net

volumes:
  postgres-data-sarpbc:
    driver: local
  redis-data-sarpbc:
    driver: local

networks:
  sarpbc_net:
    driver: bridge
