packages:
  - apps/*
  - packages/*

overrides:
  h3: 1.15.11
  fastify: 5.12.3
  prosemirror-model: 1.25.11
  prosemirror-view: 1.42.3

allowBuilds:
  "@nestjs/core": true
  "@parcel/watcher": true
  "@posthog/cli": true
  "@swc/core": true
  bcrypt: true
  core-js: true
  esbuild: true
  lefthook: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

catalog:
  typescript: ^6.0.3
  "@types/node": ^26.4.1
  nuxt: ^4.5.2
  vue: ^3.5.42
  vue-router: ^5.3.1
  vue-i18n: ^11.4.10
  "@nuxt/ui": ^4.11.0
  "@nuxtjs/i18n": ^10.6.0
  "@tiptap/core": ^3.31.3
  "@tiptap/extension-table": ^3.31.3
  "@tiptap/pm": ^3.31.3
  "@tiptap/vue-3": ^3.31.3
  vue-tsc: ^3.3.11
  "@iconify-json/fluent": ^1.2.57
  "@iconify-json/lucide": ^1.2.129
  "@iconify-json/logos": ^1.2.13
  evlog: ^2.28.1
  "@nestjs/common": ^11.2.3
  "@nestjs/core": ^11.2.3
  "@nestjs/platform-fastify": ^11.2.3
  "@nestjs/testing": ^11.2.3
  "@mikro-orm/cli": ^7.1.15
  "@mikro-orm/core": ^7.1.15
  "@mikro-orm/decorators": ^7.1.15
  "@mikro-orm/entity-generator": ^7.1.15
  "@mikro-orm/migrations": ^7.1.15
  "@mikro-orm/postgresql": ^7.1.15
  "@mikro-orm/seeder": ^7.1.15

minimumReleaseAgeExclude:
  - "@nuxt/kit@4.5.0"
  - "@nuxt/nitro-server@4.5.0"
  - "@nuxt/schema@4.5.0"
  - "@nuxt/vite-builder@4.5.0"
  - nuxt@4.5.0
  - "@posthog/core@1.45.1"
  - posthog-node@5.46.1
