export const POST_CREATION_COOLDOWN_MS = 60 * 60 * 1000;
export const POST_CREATION_COOLDOWN_HOURS = 1;

export const REPLY_CREATION_COOLDOWN_MS = 60 * 1000;

export const FORUM_ERROR_CODES = {
  POST_RATE_LIMITED: "FORUM_POST_RATE_LIMITED",
  REPLY_RATE_LIMITED: "FORUM_REPLY_RATE_LIMITED",
} as const;
