import {
  getDatabasePassword,
  getFrontUrl,
  getAdminUrl,
  getGoogleClientId,
  getGoogleClientSecret,
  getGoogleRedirectUri,
  getJwtToken,
  getPandaScoreApiToken,
  getCloudflareAccountId,
  getCloudflareApiToken,
  getCloudflareAccountHash,
  getR2AccessKeyId,
  getR2SecretAccessKey,
  getR2PublicBaseUrl,
  getR2Endpoint,
} from "src/common/envirronement/secrets";

export default () => ({
  databasePassword: getDatabasePassword(),
  jwt_token: getJwtToken(),
  google_client_secret: getGoogleClientSecret(),
  google_client_id: getGoogleClientId(),
  google_redirect_uri: getGoogleRedirectUri(),
  front_url: getFrontUrl(),
  admin_url: getAdminUrl(),
  pandascore_api_token: getPandaScoreApiToken(),
  pandascore_sync_on_boot: process.env.PANDASCORE_SYNC_ON_BOOT === "true",
  production: process.env.NODE_ENV === "production",
  port: Number(process.env.PORT ?? 4001),
  redis: {
    host: process.env.REDIS_HOST || "redis",
    port: Number(process.env.REDIS_PORT ?? 6379),
    password: process.env.REDIS_PASSWORD || undefined,
  },
  posthog: {
    token: process.env.POSTHOG_PROJECT_TOKEN,
    host: process.env.POSTHOG_HOST || "https://eu.i.posthog.com",
  },
  cloudflare_account_id: getCloudflareAccountId(),
  cloudflare_api_token: getCloudflareApiToken(),
  cloudflare_account_hash: getCloudflareAccountHash(),
  r2_account_id: process.env.R2_ACCOUNT_ID ?? getCloudflareAccountId(),
  r2_access_key_id: getR2AccessKeyId(),
  r2_secret_access_key: getR2SecretAccessKey(),
  r2_bucket: process.env.R2_BUCKET ?? "sarpbc-org",
  r2_endpoint: getR2Endpoint(),
  r2_public_base_url: getR2PublicBaseUrl(),
});
